### ISSUE TITLE
Utils 错误

### ISSUE THREAD

**Issue by mljwan** [mgsky1/DDNS#2]
Traceback (most recent call last):
  File "DDNS.py", line 3, in <module>
    from Utils import Utils
  File "/home/DDNS/Utils.py", line 3, in <module>
    import IpGetter
  File "/home/DDNS/IpGetter.py", line 2, in <module>
    import urllib.request
请问这是怎么回事啊，是哪里没调好么

**Comment by mgsky1** [comment]
不知道你用的Python版本是什么，我测试了一下，环境是Ubuntu 16.04 LTS，Python用的是3.5.2测试通过

**Comment by shaokeke** [comment]
![image](https://user-images.githubusercontent.com/37448773/58296994-953aaf00-7e08-11e9-96b2-270932354400.png)
去掉 request  import urllib
