### ISSUE TITLE
ImportError: cannot import name 'CommonRequest'

### ISSUE THREAD

**Issue by wood-j** [mgsky1/DDNS#4]
```
Traceback (most recent call last):
  File "DDNS.py", line 13, in <module>
    from Utils import Utils
  File "/root/projects/DDNS/src/Utils.py", line 15, in <module>
    from CommonRequestSingleton import CommonRequestSing
  File "/root/projects/DDNS/src/CommonRequestSingleton.py", line 6, in <module>
    from aliyunsdkcore.request import CommonRequest
ImportError: cannot import name 'CommonRequest'
```
sdk过时了？还是感谢

**Comment by mgsky1** [comment]
我刚测试了一下并没有过时啊，你可以检测一下阿里的SDK是否正确安装上了。
参考[阿里云Python SDK帮助指南](https://help.aliyun.com/document_detail/53090.html)

**Comment by coreychen** [comment]
我也遇到这个问题了， 应该是sdk更新了吧， @mgsky1  你用的是哪个版本的sdk？ 我下载的是aliyunsdkcore 1.0.3

**Comment by coreychen** [comment]
哦，是我错了，下错包了，不能下载

**Comment by VictorZhang2014** [comment]
如果您使用Python 2.x，执行以下命令，安装阿里云SDK核心库：
`pip install aliyun-python-sdk-core`

如果您使用Python 3.x，执行以下命令，安装阿里云SDK核心库：
`pip install aliyun-python-sdk-core-v3`

https://help.aliyun.com/document_detail/112147.html?spm=a2c4g.11174283.6.651.8d482c42n6uzrm

**Comment by mgsky1** [comment]
@VictorZhang2014 感谢，原来README有点老了，刚好更新一下
